require(plyr)
mydata=read.csv(file="/Users/agerho000/Desktop/output.csv", header=TRUE)
dt <- ddply(mydata,~user,summarise,mean=mean(elapsed), timeStamp=mean(timeStamp))
jpeg('resp_x_timestamp.jpg')
plot(dt$timeStamp, dt$mean)
dev.off()
jpeg('histograph.jpg')
hist(dt$mean)
dev.off()
